services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-exercise-app
    restart: always
    healthcheck:
      test: ["CMD", "wget", "localhost:3000"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - mariadb
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    networks:
      - docker-exercise

  mariadb:
    image: mariadb:11.5-rc
    container_name: mariadb
    restart: always
    env_file:
      - ./.env
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 10s
      interval: 10s
      timeout: 5s
      retries: 3
    ports:
      - "3306:3306"
    networks:
      - docker-exercise
    volumes:
      - mariadb_data:/var/lib/mysql
networks:
  docker-exercise:
    driver: bridge
volumes:
  mariadb_data:
